Traceback (most recent call last):
  File "/home/user/miniforge3/envs/book/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/miniforge3/envs/book/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/user/miniforge3/envs/book/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniforge3/envs/book/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniforge3/envs/book/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/user/miniforge3/envs/book/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/user/miniforge3/envs/book/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/user/miniforge3/envs/book/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
plot_signal_with_fft(t,y,fs,N)
------------------


[31m---------------------------------------------------------------------------[39m
[31mAttributeError[39m                            Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[6][39m[32m, line 1[39m
[32m----> [39m[32m1[39m [43mplot_signal_with_fft[49m[43m([49m[43mt[49m[43m,[49m[43my[49m[43m,[49m[43mfs[49m[43m,[49m[43mN[49m[43m)[49m

[36mCell[39m[36m [39m[32mIn[4][39m[32m, line 8[39m, in [36mplot_signal_with_fft[39m[34m(t, y, fs, N)[39m
[32m      6[39m T = N/fs [38;5;66;03m# sampling period[39;00m
[32m      7[39m y -= y.mean() [38;5;66;03m# remove DC[39;00m
[32m----> [39m[32m8[39m frq,Y = [43mspectrum[49m[43m([49m[43my[49m[43m,[49m[43mfs[49m[43m)[49m [38;5;66;03m# FFT(sampled signal)[39;00m
[32m     10[39m [38;5;66;03m# Plot[39;00m
[32m     11[39m fig, ax = plt.subplots([32m2[39m,[32m1[39m)

[36mFile [39m[32m~/Documents/GitHub/mechanical-engineering-metrology-and-measurements/book/signal_processing/../scripts/signal_processing.py:36[39m, in [36mspectrum[39m[34m(y, Fs)[39m
[32m     34[39m T = n/Fs
[32m     35[39m frq = k/T  [38;5;66;03m# two sides frequency range[39;00m
[32m---> [39m[32m36[39m frq = frq[[38;5;28mrange[39m([43mnp[49m[43m.[49m[43mint[49m(n/[32m2[39m))]  [38;5;66;03m# one side frequency range[39;00m
[32m     37[39m Y = [32m2[39m*fft.fft(y)/n  [38;5;66;03m# fft computing and normalization[39;00m
[32m     38[39m Y = Y[[38;5;28mrange[39m(np.int(n/[32m2[39m))]

[36mFile [39m[32m~/miniforge3/envs/book/lib/python3.11/site-packages/numpy/__init__.py:778[39m, in [36m__getattr__[39m[34m(attr)[39m
[32m    773[39m     warnings.warn(
[32m    774[39m         [33mf[39m[33m"[39m[33mIn the future `np.[39m[38;5;132;01m{[39;00mattr[38;5;132;01m}[39;00m[33m` will be defined as the [39m[33m"[39m
[32m    775[39m         [33m"[39m[33mcorresponding NumPy scalar.[39m[33m"[39m, [38;5;167;01mFutureWarning[39;00m, stacklevel=[32m2[39m)
[32m    777[39m [38;5;28;01mif[39;00m attr [38;5;129;01min[39;00m __former_attrs__:
[32m--> [39m[32m778[39m     [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m(__former_attrs__[attr], name=[38;5;28;01mNone[39;00m)
[32m    780[39m [38;5;28;01mif[39;00m attr [38;5;129;01min[39;00m __expired_attributes__:
[32m    781[39m     [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m(
[32m    782[39m         [33mf[39m[33m"[39m[33m`np.[39m[38;5;132;01m{[39;00mattr[38;5;132;01m}[39;00m[33m` was removed in the NumPy 2.0 release. [39m[33m"[39m
[32m    783[39m         [33mf[39m[33m"[39m[38;5;132;01m{[39;00m__expired_attributes__[attr][38;5;132;01m}[39;00m[33m"[39m,
[32m    784[39m         name=[38;5;28;01mNone[39;00m
[32m    785[39m     )

[31mAttributeError[39m: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

